version: 2

jobs:
  build:
    working_directory: ~/circleci-blueprint
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: install dependencies
          command: cd ~/corcleci-blueprint/django-rest-react-redux-blueprint/backend
      - run:
          command: pip install -r requirements.txt
      - run:
          command: python manage.py runserver

